### ISSUE TITLE
AttributeError: supported_features

### ISSUE THREAD

**Issue by guihao-liang** [nipunn1313/mypy-protobuf#364]
I'm using py3.6 from miniconda and I see the error below:

```
Successfully installed grpcio-1.37.1 grpcio-tools-1.37.1 mypy-protobuf-3.2.0 types-protobuf-3.19.15
WARNING: You are using pip version 20.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/miniconda/envs/py36/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/miniconda/envs/py36/bin/protoc-gen-mypy", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mypy_protobuf/main.py", line 106, in main
    with code_generation() as (request, response):
  File "/miniconda/envs/py36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mypy_protobuf/main.py", line 1052, in code_generation
    response.supported_features |= (
AttributeError: supported_features
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```

Does anyone know what would cause this?

**Comment by nipunn1313** [comment]
cool! glad to hear!
