### ISSUE TITLE
No module named mypy_protobuf

### ISSUE THREAD

**Issue by AaronWaxson** [nipunn1313/mypy-protobuf#470]
I install mypy_protobuf with `pip3 install mypy_protobuf`, check it with `where protoc-gen-mypy` will get `/home/user/.local/bin/protoc-gen-mypy`.
And I use `protoc --mypy_out *.proto` in terminal, can get *.pyi file succeessfully.
But when I used it in my setup.py, I'll get the error `No module named mypy_protobuf`.
Here's the example
```python
import subprocess
def generate_proto(file):
    cmd = [f"protoc -I=. --python_out=. --mypy_out=. {file}"]
    subprocess.call(cmd)
generate_proto("my.proto")
```
Any solution fot that?

**Comment by nipunn1313** [comment]
You'll probably have to provide more context / more code. What does your setup.py look like. What command are you running from your command line to run your setup.py?

From what you've shown, it seems like that should work identically to running it in the terminal.

**Comment by nipunn1313** [comment]
No module named `mypy_protobuf` seems indicative of whatever environment you're running in - it's unable to import mypy_protobuf. Some kind of installation issue or python path issue. Maybe your setup is running in a virtualenv that lacks the mypy_protobuf installation. These are all just guesses. You'll have to provide more context / try some things out.

Hopefully this points you in the right direction.

**Comment by AaronWaxson** [comment]
Here's my smallest setup.py
```python
import sys
import subprocess
from setuptools import setup
def generate_proto(file):
    cmd = [f"protoc -I=. --python_out=. --mypy_out=. {file}"]
    subprocess.call(cmd)
if __name__ == "__main__":
    sys.path.append("/home/user/.local/lib/python3.8/site_packages")
    generate_proto("my.proto")
```
I run the example with `python setup.py` it can work ,but with `pip install -e .` will report the error.
And I check the `sys.path`, shows that without `/home/user/...` related the paths, but I add local user path to the system path, it still not work.

**Comment by AaronWaxson** [comment]
I know it's not the bug, but I can not find the solution...
So hope you dont mind, and thanks for your help a lot!

**Comment by nipunn1313** [comment]
This `setup.py` did not repro the issue for me

Originally, I got this
```
➜  repro python3 setup.py
Traceback (most recent call last):
  File "/Users/nipunn/src/repro/setup.py", line 9, in <module>
    generate_proto("my.proto")
  File "/Users/nipunn/src/repro/setup.py", line 6, in generate_proto
    subprocess.call(cmd)
  File "/Users/nipunn/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/nipunn/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/nipunn/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc -I=. --python_out=. --mypy_out=. my.proto'
```

then I changed this line to fix it:
```python
    # cmd = [f"protoc -I=. --python_out=. --mypy_out=. {file}"]
    cmd = ["protoc", "-I=.", "--python_out=.", "--mypy_out=.", file]
```

Then this worked
```
➜  repro python setup.py
Writing mypy to my_pb2.pyi
```

This did not repro
```
➜  goofy pip3 install .
Processing /Users/nipunn/src/goofy
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /private/var/folders/jq/qm1fclpx4k5d9h3ytmsdtt3c0000gn/T/pip-pip-egg-info-kew03mlp
```

I am happy to help if you're able to provide a reproducible that works here, but otherwise, there's not much I can do. Try copying out the key parts and seeing if you can reproduce the error simply.

**Comment by AaronWaxson** [comment]
Sorry for wasting your much time, I am confused all the time...
I found the reason finally...its caused by project.toml...
Here's the example:
```proto
syntax = "proto2";

message Header {
  optional uint32 version = 3 [ default = 1 ];
}
```
```py
# setup.py
import sys
import subprocess
from setuptools import setup

def generate_proto(file):
    cmd = [f"protoc -I=. --python_out=. --mypy_out=. {file}"]
    subprocess.call(cmd, shell=True)


if __name__ == "__main__":
    generate_proto("header.proto")
    setup(name="test_mypy")
```
And I run it with `pip install -e .`, it worked. But when I add pyproject.toml like:
```toml
[project]
name = "test_mypy"
version = "0.0.0"

[build-system]
requires = ["setuptools>=42", "pybind11>=2.10.0"]
build-backend = "setuptools.build_meta"
```
and change setup.py like:
```py
import sys
import subprocess
from setuptools import setup

def generate_proto(file):
    cmd = [f"protoc -I=. --python_out=. --mypy_out=. {file}"]
    subprocess.call(cmd, shell=True)

if __name__ == "__main__":
    generate_proto("header.proto")
```
The error coming...
```sh
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/aaron/Projects/test/python/mypy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpe894xfuq prepare_metadata_for_build_wheel /tmp/tmp62bfr9vg
         cwd: /home/aaron/Projects/test/python/mypy
    Complete output (19 lines):
    Traceback (most recent call last):
      File "/home/aaron/.local/bin/protoc-gen-mypy", line 5, in <module>
        from mypy_protobuf.main import main
    ModuleNotFoundError: No module named 'mypy_protobuf'
    --mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
    Traceback (most recent call last):
      File "/tmp/tmpe894xfuq", line 280, in <module>
        main()
      File "/tmp/tmpe894xfuq", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpe894xfuq", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-tjj4evug/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 379, in prepare_metadata_for_build_wheel
        self._bubble_up_info_directory(metadata_directory, ".egg-info")
      File "/tmp/pip-build-env-tjj4evug/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 350, in _bubble_up_info_directory
        info_dir = self._find_info_directory(metadata_directory, suffix)
      File "/tmp/pip-build-env-tjj4evug/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 361, in _find_info_directory
        assert len(candidates) == 1, f"Multiple {suffix} directories found"
    AssertionError: Multiple .egg-info directories found
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpe894xfuq prepare_metadata_for_build_wheel /tmp/tmp62bfr9vg Check the logs for full command output.
```
Is any thought for that...?

**Comment by nipunn1313** [comment]
Congrats!! I'm happy I could be the [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging)!

Yep it sounds like inside the setup.py environment, it wasn't installed. Adding to pyproject.toml ensures it gets installed in the build environment.
